[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1206627851114389524
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "BebraLand is loading"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[init.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is currently "
	#The second line of text under the app name
	state = "Chilling in the menu"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[main_menu.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[server_list.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[realms_list.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[join_game.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently In %world%"
	#The second line of text under the app name
	state = "Playing Single Player mode"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[single_player.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% with %players% players"
	#The second line of text under the app name
	state = "Playing online"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[multi_player.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[realms.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[generic]
	#The first line of text under the app name
	description = "Playing BebraLand Create 2"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["bebralandicon"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's BebraLand Create 2 (Minecraft)"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = ["mclogo"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "BebraLand Create 2 (%mcver%)"
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "Website"
		url = "http://78.31.184.77/"

	[[generic.buttons]]
		label = "Discord"
		url = "https://discord.gg/gVmrffxDMS"


[custom]
	#Must these variables be parsed along with other variables
	enabled = false
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = true

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = ["overworld"]
		largeImageText = "In the Overworld"
		smallImageKey = ["mclogo"]
		smallImageText = "BebraLand Create 2 (%mcver%)"

		[[dimension_overrides.dimensions.buttons]]
			label = "Website"
			url = "http://78.31.184.77/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Discord"
			url = "https://discord.gg/gVmrffxDMS"


	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = ["nether"]
		largeImageText = "In the Nether"
		smallImageKey = ["mclogo"]
		smallImageText = "BebraLand Create 2 (%mcver%)"

		[[dimension_overrides.dimensions.buttons]]
			label = "Website"
			url = "http://78.31.184.77/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Discord"
			url = "https://discord.gg/gVmrffxDMS"


	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = ["the_end"]
		largeImageText = "In the End"
		smallImageKey = ["mclogo"]
		smallImageText = "BebraLand Create 2 (%mcver%)"

		[[dimension_overrides.dimensions.buttons]]
			label = "Website"
			url = "http://78.31.184.77/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Discord"
			url = "https://discord.gg/gVmrffxDMS"


	[[dimension_overrides.dimensions]]
		name = "mine"
		description = "%player% is in Mine world"
		state = ""
		largeImageKey = ["mine"]
		largeImageText = "In the Mine world"
		smallImageKey = ["mclogo"]
		smallImageText = "BebraLand Create 2 (%mcver%)"

		[[dimension_overrides.dimensions.buttons]]
			label = "Website"
			url = "http://78.31.184.77/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Discord"
			url = "https://discord.gg/gVmrffxDMS"


	[[dimension_overrides.dimensions]]
		name = "minenether"
		description = "%player% is in Mine nether world"
		state = ""
		largeImageKey = ["nether"]
		largeImageText = "In the Mine nether world"
		smallImageKey = ["mclogo"]
		smallImageText = "BebraLand Create 2 (%mcver%)"

		[[dimension_overrides.dimensions.buttons]]
			label = "Website"
			url = "http://78.31.184.77/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Discord"
			url = "https://discord.gg/gVmrffxDMS"


	[[dimension_overrides.dimensions]]
		name = "farm"
		description = "%player% is in Farm world"
		state = ""
		largeImageKey = ["farm"]
		largeImageText = "In the Farm world"
		smallImageKey = ["mclogo"]
		smallImageText = "BebraLand Create 2 (%mcver%)"

		[[dimension_overrides.dimensions.buttons]]
			label = "Website"
			url = "http://78.31.184.77/"

		[[dimension_overrides.dimensions.buttons]]
			label = "Discord"
			url = "https://discord.gg/gVmrffxDMS"



