
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				salmon = true
				glow_squid = true
				skeleton = true
				zombie = true
				bee = true
				squid = true
				wolf = true
				bat = true
				pig = true
				creeper = true
				sheep = true
				spider = true
				chicken = true
				axolotl = true
				ender_pearl = true
				enderman = true
				item = true
				cow = true
				rabbit = true

			[light_sources.settings.entities.beaver]
				beaver = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

