
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				salmon = true
				glow_squid = true
				skeleton = true
				zombie = true
				bee = true
				squid = true
				wolf = true
				bat = true
				pig = true
				creeper = true
				sheep = true
				spider = true
				chicken = true
				axolotl = true
				ender_pearl = true
				enderman = true
				item = true
				cow = true
				rabbit = true
				witch = true
				zombie_villager = true
				minecart = true
				slime = true
				arrow = true
				experience_orb = true
				tropical_fish = true
				boat = true
				potion = true
				armor_stand = true
				villager = true
				turtle = true
				dolphin = true
				evoker = true
				vex = true
				mule = true
				pillager = true
				ravager = true
				polar_bear = true
				fox = true
				cod = true
				ender_dragon = true
				drowned = true
				horse = true
				eye_of_ender = true
				llama = true
				donkey = true
				trader_llama = true
				wandering_trader = true
				firework_rocket = true

			[light_sources.settings.entities.beaver]
				beaver = true
				create_beaver = true
				beaver_with_glasses = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.enigmaticgraves]
				grave = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.strawstatues]
				straw_statue = true

			[light_sources.settings.entities.hedgehog]
				hedgehog = true

