
#Turtle Charging Station Configuration
[turtlechargingstation]
	#The maximum amount of FE the charging station can hold
	#Range: > 0
	maxCapacity = 128000
	#The amount of FE required to increase the turtle fuel level by 1
	#Range: > 0
	conversionRate = 300

